# Question 1

a. Consider the following dataset. Split the data into a 30-70 test-training set

In [8]:
import seaborn as sns
diamonds = sns.load_dataset('diamonds')
data = diamonds.to_numpy()
y = data[:,6]
X = data[:,(0,4,5,7,8,9)] # restrict ourselves to real numbers only

diamonds.head()

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75


In [9]:
# import math, random
# def create_test_train_indicies(fraction_train, data_nrow):
#   train_indicies, test_indicies = [],[]

#   total_test_int = int((1-fraction_train) * data_nrow)

#   for i in range(total_test_int):
#     math.random


#   return train_indicies, test_indicies



import math, random
def create_test_train_indicies(fraction_train, data_nrow):


  training_set_size = math.floor(0.8 * data_nrow)
  training_set_size


  random.seed(1) # this makes randomness repeatible
  train_indicies = random.sample(range(data_nrow), training_set_size)

  test_indicies = list(range(data_nrow))
  for i in train_indicies:
    test_indicies.remove(i)
  len(test_indicies)


  return train_indicies, test_indicies

In [11]:
random.seed(1)

train_indicies, test_indicies = create_test_train_indicies(.7, X.shape[0])

X_train = X[train_indicies,:]
X_test = X[test_indicies,:]
y_train = y[train_indicies]
y_test = y[test_indicies]

b. Fit a linear model to the data

In [12]:
def MSE(prediction_errors):
  return sum(prediction_errors ** 2) / len(prediction_errors)

In [14]:
from sklearn.linear_model import LinearRegression

fitted_model = LinearRegression().fit(X_train, y_train)
train_error = MSE(fitted_model.predict(X_train) - y_train)
test_error = MSE(fitted_model.predict(X_test) - y_test)

c. What do you estimate the MSE to be on unseen data?

In [15]:
test_error

2288309.632915307

# Question 2

a. Using the math package write a function to compute $(x_0 + \exp(x_0) + x_1)^3$






In [29]:
def my_func(X):
  return (X[0] + math.exp(X[0])+X[1])**3

In [30]:
# test function
import numpy as np
assert my_func(np.array([0, 0])) == 1.0
assert abs(my_func(np.array([0.1, 0.2])) - 2.7745174378) < 1e-5

b. Compute the derivative of the function at $x_0 = 1, x_1 = 1$ with respect to $x_1$ using finite differences


In [40]:
def multivar_finite_diff(func, var, h):
  h_point = [var[0], var[1] + h]
  return (func(h_point) - func(var)) / h

In [41]:
multivar_finite_diff(my_func, [1,1], h=1e-5)

66.78669179080998

c. Reimplement the function in pytorch


In [78]:
import torch
def my_pytorch_func(x):
  return torch.pow(x[0] + torch.exp(x[0])+x[1],3)


In [79]:
# test function
assert my_pytorch_func(torch.tensor([0, 0])) == 1.0
assert abs(my_pytorch_func(torch.tensor([0.1, 0.2])) - 2.7745174378) < 1e-5

d. Recompute the derivative from (b) using pytorch


In [80]:
x0_val = torch.ones(1, requires_grad=False) # requires_grad=True means differentiate with respect to this tensor
x0_val
x1_val = torch.ones(1, requires_grad=True)
x1_val

f = my_pytorch_func([x0_val,x1_val]) # forward pass
f
f.backward()

In [81]:
x1_val.grad

tensor([66.7865])

e. Using pytorch compute the derivative with respect to $x_0$ at $x_0 = -1, x_1 = 1$.

In [83]:

x_new = torch.tensor([-1.0,1.0], requires_grad = True)

#x1_val = torch.ones(1, requires_grad=False)
#x1_val

f = my_pytorch_func(x_new) # forward pass
f
f.backward()
x_new.grad[0]


tensor(0.5554)

## Question 3

a. Write a function to compute $f(x,y) = y^T A x$ where A is defined to be

In [120]:
import random, numpy as np
random.seed(1)
A = np.random.random((5,8)) # creates a randomly generated matrix
def compute_fxy(x, y):
  return np.dot(y, np.matmul(A,x))

b. Evaluate $f$ at the points:

In [123]:
# i.
random.seed(1)
x = np.ones(8)
y = np.ones(5)

f = compute_fxy(x,y)
f

np.float64(23.80224695007989)

In [124]:
# ii.
random.seed(1)
x = np.array([40.0, 4.0, 3.0, 1.0, 2.0, 3.0, 0.0, 0.0])
y = np.array([0.5, 0.1, 0.3, 0.0, 0.4])

f = compute_fxy(x,y)
f

np.float64(46.98041048718286)

c. Write a function that analytically computes the derivatives of $f$. Compute the derivatives at point i. and ii.

In [125]:
# deri of f_xy w resp to x is yT*A
# deriv of f_xy w resp to y is A*x
def derivative_of_fxy_with_respect_to_y(x, y):
  return np.matmul(y,A), np.matmul(A,x)


In [126]:
# i.
x = np.ones(8)
y = np.ones(5)
derivative_of_fxy_with_respect_to_y(x, y)

(array([3.10589512, 2.95097229, 2.790627  , 3.29625401, 2.27996277,
        3.50351076, 2.75300731, 3.12201769]),
 array([4.93099798, 4.30438596, 3.95592415, 5.74781582, 4.86312303]))

In [128]:
# ii.
x = np.array([40.0, 4.0, 3.0, 1.0, 2.0, 3.0, 0.0, 0.0])
y = np.array([0.5, 0.1, 0.3, 0.0, 0.4])
derivative_of_fxy_with_respect_to_y(x, y)

(array([0.95587797, 0.65369521, 0.57252032, 0.75948901, 0.62612008,
        0.80040694, 0.98992224, 0.66993228]),
 array([44.6653757 , 20.55227055, 22.12159928, 35.54900162, 39.89003949]))

d. Compute the derivative of $f$ at the points from part b. using pytorch and compare it with the value given in part c.

In [136]:
import torch
A_torch = torch.tensor(A)
def torch_compute_fxy(x, y):
  return torch.dot(y, torch.matmul(A_torch,x))

In [139]:
# i.
torch.manual_seed(0)
x = torch.tensor(np.ones(8), requires_grad=True)
y = torch.tensor(np.ones(5), requires_grad=True)
f = torch_compute_fxy(x, y)
f.backward()
print(x.grad)
print(y.grad)

tensor([3.1059, 2.9510, 2.7906, 3.2963, 2.2800, 3.5035, 2.7530, 3.1220],
       dtype=torch.float64)
tensor([4.9310, 4.3044, 3.9559, 5.7478, 4.8631], dtype=torch.float64)


In [140]:
# ii.
torch.manual_seed(0)

torch_compute_fxy(x,y).backward()
########
# TODO #
########
print(x.grad)
print(y.grad)

tensor([6.2118, 5.9019, 5.5813, 6.5925, 4.5599, 7.0070, 5.5060, 6.2440],
       dtype=torch.float64)
tensor([ 9.8620,  8.6088,  7.9118, 11.4956,  9.7262], dtype=torch.float64)
